package GUI;
import Program.enums.ExpenseCategory; import Program.model.*; import Program.service.*; import javafx.beans.property.SimpleStringProperty; import javafx.collections.FXCollections; import javafx.scene.control.*; import javafx.scene.layout.*; import java.time.LocalDate; import java.util.Arrays;
public class BudgetUI extends ScrollPane {
 private final User user; private final BudgetService service=new BudgetService(); private final TransactionService transactions=new TransactionService(); private final TableView<Budget> table=new TableView<>();
 public BudgetUI(User user,MainUI app){this.user=user;setFitToWidth(true);VBox p=UIFactory.page("Budgets","Set spending limits and monitor usage in real time.");Button add=UIFactory.button("+ Add Budget","primary-button");add.setOnAction(e->edit(null));setup();refresh();p.getChildren().addAll(add,table);setContent(p);}
 private void setup(){table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY_FLEX_NEXT_COLUMN);column("Category",Budget::getCategory);column("Limit",b->money(b.getLimit()));column("Current spending",b->money(spending(b)));column("Remaining",b->money(b.remaining(spending(b))));column("Usage",b->String.format("%.0f%%",b.usage(spending(b))*100));TableColumn<Budget,Void> actions=new TableColumn<>("Actions");actions.setCellFactory(c->new TableCell<>(){final Button edit=UIFactory.button("Edit","secondary-button"),delete=UIFactory.button("Delete","danger-button");final HBox buttons=new HBox(5,edit,delete);{edit.setOnAction(e->BudgetUI.this.edit(getTableView().getItems().get(getIndex())));delete.setOnAction(e->{service.delete(getTableView().getItems().get(getIndex()).getId());refresh();});}@Override protected void updateItem(Void item,boolean empty){super.updateItem(item,empty);setGraphic(empty?null:buttons);}});table.getColumns().add(actions);}
 private void column(String title,java.util.function.Function<Budget,String> value){TableColumn<Budget,String>c=new TableColumn<>(title);c.setCellValueFactory(x->new SimpleStringProperty(value.apply(x.getValue())));table.getColumns().add(c);} private double spending(Budget b){return transactions.expenseByCategory(user.getId(),LocalDate.now().withDayOfMonth(1),LocalDate.now()).getOrDefault(b.getCategory(),0d);} private String money(double v){return String.format("৳%,.0f",v);} private void refresh(){table.setItems(FXCollections.observableArrayList(service.load(user.getId())));}
 private void edit(Budget old){Dialog<ButtonType>d=new Dialog<>();d.setTitle(old==null?"Add Budget":"Edit Budget");ComboBox<String>cat=new ComboBox<>();cat.getItems().addAll(Arrays.stream(ExpenseCategory.values()).map(ExpenseCategory::getLabel).toList());TextField limit=UIFactory.field("Monthly limit");if(old!=null){cat.setValue(old.getCategory());limit.setText(String.valueOf(old.getLimit()));}GridPane form=new GridPane();form.setHgap(10);form.setVgap(10);form.addRow(0,new Label("Category"),cat);form.addRow(1,new Label("Limit"),limit);d.getDialogPane().setContent(form);d.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);d.showAndWait().filter(x->x==ButtonType.OK).ifPresent(x->{try{if(cat.getValue()==null)throw new IllegalArgumentException("Please select a category.");double amount=Program.utils.Validator.positiveAmount(limit.getText());if(old==null)service.add(user.getId(),cat.getValue(),amount);else service.update(old,cat.getValue(),amount);refresh();}catch(Exception ex){UIFactory.error(ex.getMessage());}});}
}
