package GUI;
import Program.model.Income; import Program.model.User; import Program.service.*; import Program.utils.AIResponseFormatter; import javafx.concurrent.Task; import javafx.geometry.*; import javafx.scene.control.*; import javafx.scene.layout.*; import javafx.scene.shape.SVGPath; import java.time.LocalDate; import java.util.Map;
public class FinancialAdvisorUI extends BorderPane {private final VBox messages=new VBox(12);private final ScrollPane scroll=new ScrollPane(messages);
 public FinancialAdvisorUI(User user,MainUI app){setPadding(new Insets(28,32,28,32));Button back=UIFactory.button("← Back","secondary-button");back.setOnAction(e->app.navigate("AI Intelligence"));Button clear=UIFactory.button("Clear conversation","secondary-button");clear.setOnAction(e->messages.getChildren().clear());Region space=new Region();HBox.setHgrow(space,Priority.ALWAYS);Label title=UIFactory.title("Financial Advisor");SVGPath titleIcon=new SVGPath();titleIcon.setContent("M4,4 L20,4 L20,16 L9,16 L4,20 L4,4 Z M8,9 L16,9 L16,11 L8,11 Z");titleIcon.getStyleClass().add("ai-heading-icon");title.setGraphic(titleIcon);title.setContentDisplay(ContentDisplay.LEFT);title.setGraphicTextGap(10);VBox heading=new VBox(12,new HBox(10,back,space,clear),title,UIFactory.muted("General, data-aware guidance — not professional financial advice."));heading.setMaxWidth(768);StackPane headingWrap=new StackPane(heading);headingWrap.setAlignment(Pos.TOP_CENTER);setTop(headingWrap);
  messages.setPadding(new Insets(18));messages.setMaxWidth(768);messages.getChildren().add(bubble("AI","Ask a question about your spending, savings, budgets, or financial habits.",false));scroll.setFitToWidth(true);scroll.setMaxWidth(768);scroll.getStyleClass().add("chat-area");StackPane chatWrap=new StackPane(scroll);chatWrap.setAlignment(Pos.TOP_CENTER);chatWrap.setPadding(new Insets(18,0,14,0));setCenter(chatWrap);
  TextArea input=new TextArea();input.setPromptText("Ask a financial question…");input.setWrapText(true);input.setPrefRowCount(1);input.setMinHeight(48);input.setMaxHeight(104);input.getStyleClass().add("advisor-input");Button send=UIFactory.button("","send-button");send.setAccessibleText("Send message");SVGPath arrow=new SVGPath();arrow.setContent("M12 2.8c-1.2 0-2.1.6-2.9 1.7L2.5 14.2c-1.5 2.2.5 5 3 4.1l4.6-1.8v-5.3c0-1.1.8-2 1.9-2s1.9.9 1.9 2v5.3l4.6 1.8c2.5.9 4.5-1.9 3-4.1L14.9 4.5C14.1 3.4 13.2 2.8 12 2.8zm-1.1 8.4h2.2v5.2l-1.1.45-1.1-.45v-5.2z");arrow.getStyleClass().add("send-arrow");send.setGraphic(arrow);HBox pill=new HBox(8,input,send);pill.setAlignment(Pos.CENTER);pill.setMaxWidth(768);HBox.setHgrow(input,Priority.ALWAYS);pill.getStyleClass().add("input-pill");StackPane inputWrap=new StackPane(pill);inputWrap.setAlignment(Pos.CENTER);setBottom(inputWrap);send.setOnAction(e->send(user,input,send));input.setOnKeyPressed(e->{if(e.isControlDown()&&e.getCode()==javafx.scene.input.KeyCode.ENTER)send.fire();});}
 private void send(User user,TextArea input,Button send){String question=input.getText().trim();if(question.isEmpty())return;input.clear();messages.getChildren().add(bubble("You",question,true));HBox loading=bubble("AI","Thinking…",false);messages.getChildren().add(loading);send.setDisable(true);Task<String>task=new Task<>(){@Override protected String call(){return new AIService().advisor(user.getId(),question);}};task.setOnSucceeded(e->{messages.getChildren().remove(loading);messages.getChildren().add(bubble("AI",formatAdvisorResponse(task.getValue(),user),false));send.setDisable(false);scroll.setVvalue(1);});task.setOnFailed(e->{messages.getChildren().remove(loading);messages.getChildren().add(bubble("AI",AIResponseFormatter.sanitizeAIResponse(task.getException().getMessage()),false));send.setDisable(false);});Thread thread=new Thread(task,"ai-advisor");thread.setDaemon(true);thread.start();}
 private String formatAdvisorResponse(String response,User user){TransactionService transactions=new TransactionService();BudgetService budgets=new BudgetService();LocalDate monthStart=LocalDate.now().withDayOfMonth(1);Map<String,Double> spending=transactions.expenseByCategory(user.getId(),monthStart,LocalDate.now());double income=transactions.all(user.getId()).stream().filter(transaction->transaction instanceof Income&&!transaction.getDate().isBefore(monthStart)).mapToDouble(transaction->transaction.getAmount()).sum();double balance=income-spending.values().stream().mapToDouble(Double::doubleValue).sum();return AIResponseFormatter.formatSpendingSummary(response,spending,budgets.load(user.getId()),balance);}private HBox bubble(String who,String text,boolean mine){Label label=new Label(who+"\n"+text);label.setWrapText(true);label.setMaxWidth(510);label.getStyleClass().add(mine?"user-bubble":"ai-bubble");HBox row=new HBox(label);row.setMaxWidth(Double.MAX_VALUE);row.setAlignment(mine?Pos.CENTER_RIGHT:Pos.CENTER_LEFT);row.getStyleClass().add(mine?"user-message-row":"ai-message-row");return row;}
}
