package Program.service;
import Program.enums.UserRole; import Program.model.User; import Program.utils.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.util.*;
public class AuthService {
 public User register(String name,String username,String password,String confirm){if(Validator.blank(name)||Validator.blank(username)||Validator.blank(password))throw new IllegalArgumentException("Name, username and password are required.");if(!password.equals(confirm))throw new IllegalArgumentException("Passwords do not match.");if(findByUsername(username).isPresent())throw new IllegalArgumentException("That username is already in use.");User u=new User(UUID.randomUUID().toString(),FileManager.clean(name),FileManager.clean(username),hash(password),UserRole.USER);FileManager.append("users.txt",record(u));return u;}
 public User login(String username,String password){User u=findByUsername(username).orElseThrow(()->new IllegalArgumentException("Invalid username or password."));if(!u.getPasswordHash().equals(hash(password)))throw new IllegalArgumentException("Invalid username or password.");SessionManager.login(u);return u;}
 public void changePassword(User u,String oldPassword,String newPassword){if(!u.getPasswordHash().equals(hash(oldPassword)))throw new IllegalArgumentException("Current password is incorrect.");if(Validator.blank(newPassword))throw new IllegalArgumentException("New password is required.");u.setPasswordHash(hash(newPassword));FileManager.update("users.txt",s->s.startsWith(u.getId()+"|"),record(u));}
 public void updateProfile(User u,String name){if(Validator.blank(name))throw new IllegalArgumentException("Name is required.");u.setFullName(FileManager.clean(name));FileManager.update("users.txt",s->s.startsWith(u.getId()+"|"),record(u));}
 private Optional<User> findByUsername(String username){return FileManager.read("users.txt").stream().map(this::parse).filter(Objects::nonNull).filter(u->u.getUsername().equalsIgnoreCase(username==null?"":username.trim())).findFirst();}
 private User parse(String s){try{String[] p=s.split("\\|",-1);return p.length==5?new User(p[0],p[3],p[1],p[2],UserRole.valueOf(p[4])):null;}catch(Exception e){return null;}}
 private String record(User u){return String.join("|",u.getId(),u.getUsername(),u.getPasswordHash(),u.getFullName(),u.getRole().name());}
 public static String hash(String value){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(value.getBytes(StandardCharsets.UTF_8));StringBuilder out=new StringBuilder();for(byte x:b)out.append(String.format("%02x",x));return out.toString();}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
